services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      DATABASE_URI: ${DATABASE_URI}
      DATABASE_NAME: ${DATABASE_NAME}
      RABBITMQ_CONNECTION_STRING: ${RABBITMQ_CONNECTION_STRING}
    networks:
      - app-network
    restart: always

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_CONNECTION_STRING: ${RABBITMQ_CONNECTION_STRING}
      API_BASE_URL: ${API_BASE_URL}
    ports:
      - "8081:8080"
    restart: always
    networks:
      - app-network

volumes:
  rabbitmq_data:

networks:
  app-network:
