services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    env_file:
      - ./api/.env
    restart: always

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging
      - "15672:15672" # RabbitMQ Management GUI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: securepassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: "amqp://admin:securepassword@rabbitmq:5672/"
      API_BASE_URL: "http://api:8080/"
    ports:
      - "8081:8080"
    restart: always

volumes:
  rabbitmq_data:
